### PR TITLE
Improve project settings' manageability

### PR DESCRIPTION
**Pull request by cezarypiatek**
I've changed a couple of o things:

- Added sln file to facilitate project development in Visual Studio and Rider. This also simplify CI script and helps to avoid situation when somebody adds another test project and forgot to add it in CI definition.

- Move common settings to `Directory.Build.props` file. This will simplify changing properties in the future and enforce consistency across all the projects.

- Enable code analysis on the build to enforce all configured rules in CI

### CODE REVIEW

**Comment by lkurzyniec** [comment]
I develop it without sln on purpose. Sln works on Win (VS) and Mac (VS on Mac), but it doesn't on Linux. My intention is to be available as much as possible with that project/repo.
On the other hand, the sln file doesn't break anything, so later on I will merge your PR. Thanks for your contribution!

**Comment by lkurzyniec** [comment]
@cezarypiatek I also give a try with `Directory.Build.props` after our discussion on twitter, but it won't work for me without sln. Now it should works :)

**Comment by cezarypiatek** [comment]
What's wrong with SLN on Linux? Dotnet CLI contains a set of commands related to SLN files https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln and according to my knowledge, Jetbrains Rider also works on Linux?

**Comment by lkurzyniec** [comment]
Now I see there is nothing wrong with sln, I didn't know that dotnet CLI works with sln, so my lack of knowledge ;)

**Pull request merged**
